### ISSUE TITLE
Issues running 'npm install`

### ISSUE THREAD

**Issue by Lakhankumawat** [vrii14/Land-Registration-with-Blockchain#4]
## Node Version : 
```
node --version
v16.14.2
```

## Npm Version : 
```
npm --version
8.6.0
```

## Complete Logs : 
```
F:\BlockChain Apps\Land-Registration-with-Blockchain>cd client

F:\BlockChain Apps\Land-Registration-with-Blockchain\client>npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN old lockfile Error: git dep preparation failed
npm WARN old lockfile     at ChildProcess.<anonymous> (C:\Users\kumaw\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
npm WARN old lockfile     at ChildProcess.emit (node:events:526:28)
npm WARN old lockfile     at maybeClose (node:internal/child_process:1092:16)
npm WARN old lockfile     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm WARN old lockfile  Could not fetch metadata for websocket@git+ssh://git@github.com/frozeman/WebSocket-Node.git#6c72925e3f8aaaea8dc8450f97627e85263999f2 Error: git dep preparation failed
npm WARN old lockfile     at ChildProcess.<anonymous> (C:\Users\kumaw\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
npm WARN old lockfile     at ChildProcess.emit (node:events:526:28)
npm WARN old lockfile     at maybeClose (node:internal/child_process:1092:16)
npm WARN old lockfile     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
npm WARN old lockfile   cmd: 'C:\\Program Files\\nodejs\\node.exe',
npm WARN old lockfile   args: [
npm WARN old lockfile     'C:\\Users\\kumaw\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm WARN old lockfile     'install',
npm WARN old lockfile     '--force',
npm WARN old lockfile     '--cache=C:\\Users\\kumaw\\AppData\\Local\\npm-cache',
npm WARN old lockfile     '--prefer-offline=false',
npm WARN old lockfile     '--prefer-online=false',
npm WARN old lockfile     '--offline=false',
npm WARN old lockfile     '--no-progress',
npm WARN old lockfile     '--no-save',
npm WARN old lockfile     '--no-audit',
npm WARN old lockfile     '--include=dev',
npm WARN old lockfile     '--include=peer',
npm WARN old lockfile     '--include=optional',
npm WARN old lockfile     '--no-package-lock-only',
npm WARN old lockfile     '--no-dry-run'
npm WARN old lockfile   ],
npm WARN old lockfile   code: 1,
npm WARN old lockfile   signal: null,
npm WARN old lockfile   stdout: '',
npm WARN old lockfile   stderr: 'npm WARN using --force Recommended protections disabled.\n' +
npm WARN old lockfile     'npm ERR! code 1\n' +
npm WARN old lockfile     'npm ERR! The git reference could not be found\n' +
npm WARN old lockfile     'npm ERR! command git --no-replace-objects checkout 4.0\n' +
npm WARN old lockfile     "npm ERR! error: pathspec '4.0' did not match any file(s) known to git\n" +
npm WARN old lockfile     '\n' +
npm WARN old lockfile     'npm ERR! A complete log of this run can be found in:\n' +
npm WARN old lockfile     'npm ERR!     C:\\Users\\kumaw\\AppData\\Local\\npm-cache\\_logs\\2022-04-12T12_56_41_342Z-debug-0.log\n'
npm WARN old lockfile }
npm WARN deprecated safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated promisify-es6@1.0.3: Unmaintained
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated ethereumjs-tx@2.1.2: New package name format for new versions: @ethereumjs/tx. Please update.
npm WARN deprecated multicodec@1.0.4: This module has been superseded by the multiformats module
npm WARN deprecated uuid@2.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated multibase@0.6.1: This module has been superseded by the multiformats module
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated multibase@0.7.0: This module has been superseded by the multiformats module
npm WARN deprecated multibase@0.6.1: This module has been superseded by the multiformats module
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated ethereumjs-tx@1.3.7: New package name format for new versions: @ethereumjs/tx. Please update.
npm WARN deprecated multicodec@0.5.7: This module has been superseded by the multiformats module
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated react-s-alert@1.4.1: No longer maintained, see more info in readme
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated emailjs-com@2.6.4: The SDK name changed to @emailjs/browser
npm WARN deprecated protons@1.2.1: This module is no longer maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated multihashing-async@0.5.2: This module has been superseded by the multiformats module
npm WARN deprecated libp2p-crypto-secp256k1@0.2.3: Included in libp2p-crypto, use it instead. https://github.com/libp2p/js-libp2p-crypto
npm WARN deprecated multibase@0.5.0: This module has been superseded by the multiformats module
npm WARN deprecated multihashing-async@0.6.0: This module has been superseded by the multiformats module
npm WARN deprecated ipld-dag-cbor@0.13.1: This module has been superseded by @ipld/dag-cbor and multiformats
npm WARN deprecated ipld-dag-pb@0.14.11: This module has been superseded by @ipld/dag-pb and multiformats
npm WARN deprecated multihashing-async@0.4.8: This module has been superseded by the multiformats module
npm WARN deprecated ethereumjs-common@1.5.2: New package name format for new versions: @ethereumjs/common. Please update.
npm WARN deprecated cids@0.5.8: This module has been superseded by the multiformats module
npm WARN deprecated cids@0.5.8: This module has been superseded by the multiformats module
npm WARN deprecated cids@0.5.8: This module has been superseded by the multiformats module
npm WARN deprecated cids@0.5.8: This module has been superseded by the multiformats module
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated libp2p-crypto-secp256k1@0.3.1: Included in libp2p-crypto, use it instead. https://github.com/libp2p/js-libp2p-crypto
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated cids@0.7.5: This module has been superseded by the multiformats module
npm WARN deprecated @material-ui/system@4.11.3: You can now upgrade to @mui/system. See the guide: https://mui.com/guides/migration-v4/
npm WARN deprecated peer-info@0.14.1: No longer supported for js-libp2p0.28.0 or later
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated @material-ui/styles@4.11.3: You can now upgrade to @mui/styles. See the guide: https://mui.com/guides/migration-v4/
npm WARN deprecated ipfs-api@26.1.2: ipfs-api has been renamed to ipfs-http-client, please update your package.json to get the latest version.
npm WARN deprecated core-js@1.2.7: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated @material-ui/core@4.11.3: You can now upgrade to @mui/material. See the guide: https://mui.com/guides/migration-v4/
Terminate batch job (Y/N)? n

F:\BlockChain Apps\Land-Registration-with-Blockchain\client>npm start

> client@0.1.0 start
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.

F:\BlockChain Apps\Land-Registration-with-Blockchain\client>npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN old lockfile Error: git dep preparation failed
npm WARN old lockfile     at ChildProcess.<anonymous> (C:\Users\kumaw\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
npm WARN old lockfile     at ChildProcess.emit (node:events:526:28)
npm WARN old lockfile     at maybeClose (node:internal/child_process:1092:16)
npm WARN old lockfile     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm WARN old lockfile  Could not fetch metadata for websocket@git+ssh://git@github.com/frozeman/WebSocket-Node.git#6c72925e3f8aaaea8dc8450f97627e85263999f2 Error: git dep preparation failed
npm WARN old lockfile     at ChildProcess.<anonymous> (C:\Users\kumaw\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
npm WARN old lockfile     at ChildProcess.emit (node:events:526:28)
npm WARN old lockfile     at maybeClose (node:internal/child_process:1092:16)
npm WARN old lockfile     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
npm WARN old lockfile   cmd: 'C:\\Program Files\\nodejs\\node.exe',
npm WARN old lockfile   args: [
npm WARN old lockfile     'C:\\Users\\kumaw\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm WARN old lockfile     'install',
npm WARN old lockfile     '--force',
npm WARN old lockfile     '--cache=C:\\Users\\kumaw\\AppData\\Local\\npm-cache',
npm WARN old lockfile     '--prefer-offline=false',
npm WARN old lockfile     '--prefer-online=false',
npm WARN old lockfile     '--offline=false',
npm WARN old lockfile     '--no-progress',
npm WARN old lockfile     '--no-save',
npm WARN old lockfile     '--no-audit',
npm WARN old lockfile     '--include=dev',
npm WARN old lockfile     '--include=peer',
npm WARN old lockfile     '--include=optional',
npm WARN old lockfile     '--no-package-lock-only',
npm WARN old lockfile     '--no-dry-run'
npm WARN old lockfile   ],
npm WARN old lockfile   code: 1,
npm WARN old lockfile   signal: null,
npm WARN old lockfile   stdout: '',
npm WARN old lockfile   stderr: 'npm WARN using --force Recommended protections disabled.\n' +
npm WARN old lockfile     'npm ERR! code 1\n' +
npm WARN old lockfile     'npm ERR! The git reference could not be found\n' +
npm WARN old lockfile     'npm ERR! command git --no-replace-objects checkout 4.0\n' +
npm WARN old lockfile     "npm ERR! error: pathspec '4.0' did not match any file(s) known to git\n" +
npm WARN old lockfile     '\n' +
npm WARN old lockfile     'npm ERR! A complete log of this run can be found in:\n' +
npm WARN old lockfile     'npm ERR!     C:\\Users\\kumaw\\AppData\\Local\\npm-cache\\_logs\\2022-04-12T13_11_35_850Z-debug-0.log\n'
npm WARN old lockfile }
npm WARN deprecated safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated promisify-es6@1.0.3: Unmaintained
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated multicodec@1.0.4: This module has been superseded by the multiformats module
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated multibase@0.6.1: This module has been superseded by the multiformats module
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated react-s-alert@1.4.1: No longer maintained, see more info in readme
npm WARN deprecated ethereumjs-tx@1.3.7: New package name format for new versions: @ethereumjs/tx. Please update.
npm WARN deprecated multicodec@0.5.7: This module has been superseded by the multiformats module
npm WARN deprecated emailjs-com@2.6.4: The SDK name changed to @emailjs/browser
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated multihashing-async@0.5.2: This module has been superseded by the multiformats module
npm WARN deprecated libp2p-crypto-secp256k1@0.2.3: Included in libp2p-crypto, use it instead. https://github.com/libp2p/js-libp2p-crypto
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated ipld-dag-cbor@0.13.1: This module has been superseded by @ipld/dag-cbor and multiformats
npm WARN deprecated protons@1.2.1: This module is no longer maintained
npm WARN deprecated ipld-dag-pb@0.14.11: This module has been superseded by @ipld/dag-pb and multiformats
npm WARN deprecated ethereumjs-common@1.5.2: New package name format for new versions: @ethereumjs/common. Please update.
npm WARN deprecated @material-ui/system@4.11.3: You can now upgrade to @mui/system. See the guide: https://mui.com/guides/migration-v4/
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated cids@0.7.5: This module has been superseded by the multiformats module
npm WARN deprecated peer-info@0.14.1: No longer supported for js-libp2p0.28.0 or later
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated @material-ui/styles@4.11.3: You can now upgrade to @mui/styles. See the guide: https://mui.com/guides/migration-v4/
npm WARN deprecated ipfs-api@26.1.2: ipfs-api has been renamed to ipfs-http-client, please update your package.json to get the latest version.
npm WARN deprecated core-js@1.2.7: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated @material-ui/core@4.11.3: You can now upgrade to @mui/material. See the guide: https://mui.com/guides/migration-v4/
npm ERR! code 1
npm ERR! path F:\BlockChain Apps\Land-Registration-with-Blockchain\client\node_modules\scrypt
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.14.2 | win32 | x64
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Program Files\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:399:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\BlockChain Apps\\Land-Registration-with-Blockchain\\client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd F:\BlockChain Apps\Land-Registration-with-Blockchain\client\node_modules\scrypt
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kumaw\AppData\Local\npm-cache\_logs\2022-04-12T13_10_02_593Z-debug-0.log

F:\BlockChain Apps\Land-Registration-with-Blockchain\client>npm run start

> client@0.1.0 start
> react-scripts start

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'react-dev-utils/crossSpawn'
Require stack:
- F:\BlockChain Apps\Land-Registration-with-Blockchain\client\node_modules\react-scripts\bin\react-scripts.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (F:\BlockChain Apps\Land-Registration-with-Blockchain\client\node_modules\react-scripts\bin\react-scripts.js:18:15)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'F:\\BlockChain Apps\\Land-Registration-with-Blockchain\\client\\node_modules\\react-scripts\\bin\\react-scripts.js'
  ]
}

F:\BlockChain Apps\Land-Registration-with-Blockchain\client>

```

**Comment by alenpaulvarghese** [comment]
check the new pull request

**Comment by minnat65** [comment]
Hello @alenpaulvarghese @Lakhankumawat 

Facing the same error.

npm WARN old lockfile Error: git dep preparation failed
npm WARN old lockfile     at ChildProcess.<anonymous> (/home/minnat/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
npm WARN old lockfile     at ChildProcess.emit (node:events:513:28)
npm WARN old lockfile     at maybeClose (node:internal/child_process:1091:16)
npm WARN old lockfile     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm WARN old lockfile  Could not fetch metadata for websocket@git+ssh://git@github.com/frozeman/WebSocket-Node.git#6c72925e3f8aaaea8dc8450f97627e85263999f2 Error: git dep preparation failed
npm WARN old lockfile     at ChildProcess.<anonymous> (/home/minnat/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
npm WARN old lockfile     at ChildProcess.emit (node:events:513:28)
npm WARN old lockfile     at maybeClose (node:internal/child_process:1091:16)
npm WARN old lockfile     at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
npm WARN old lockfile   cmd: '/home/minnat/.nvm/versions/node/v18.8.0/bin/node',
npm WARN old lockfile   args: [
npm WARN old lockfile     '/home/minnat/.nvm/versions/node/v18.8.0/lib/node_modules/npm/bin/npm-cli.js',
npm WARN old lockfile     'install',
npm WARN old lockfile     '--force',
npm WARN old lockfile     '--cache=/home/minnat/.npm',
npm WARN old lockfile     '--prefer-offline=false',
npm WARN old lockfile     '--prefer-online=false',
npm WARN old lockfile     '--offline=false',
npm WARN old lockfile     '--no-progress',
npm WARN old lockfile     '--no-save',
npm WARN old lockfile     '--no-audit',
npm WARN old lockfile     '--include=dev',
npm WARN old lockfile     '--include=peer',
npm WARN old lockfile     '--include=optional',
npm WARN old lockfile     '--no-package-lock-only',
npm WARN old lockfile     '--no-dry-run'
npm WARN old lockfile   ],
npm WARN old lockfile   code: 1,
npm WARN old lockfile   signal: null,
npm WARN old lockfile   stdout: '',
npm WARN old lockfile   stderr: 'npm WARN using --force Recommended protections disabled.\n' +
npm WARN old lockfile     'npm ERR! code 1\n' +
npm WARN old lockfile     'npm ERR! The git reference could not be found\n' +
npm WARN old lockfile     'npm ERR! command git --no-replace-objects checkout 4.0\n' +
npm WARN old lockfile     "npm ERR! error: pathspec '4.0' did not match any file(s) known to git\n" +
npm WARN old lockfile     '\n' +
npm WARN old lockfile     'npm ERR! A complete log of this run can be found in:\n' +
npm WARN old lockfile     'npm ERR!     /home/minnat/.npm/_logs/2023-06-06T05_48_54_099Z-debug-0.log\n'
npm WARN old lockfile }

**Comment by alenpaulvarghese** [comment]
Hi @minnat65,

The project is really old and have many broken dependencies.
You can clone my PR and update the dependencies if you want to make it work.

**Comment by bucky1947** [comment]
Hi @alenpaulvarghese , please create a docker image for this application, there is alot of issues from installing package.json to npm start, it would be a great contribution,

**Comment by Surajbodke** [comment]
Hi @bucky1947, did you resolve the problem
